name: CI - DB - Staging

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflows }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: "Deploy Staging DB"
    environment: AWS Staging DB
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - run: corepack enable pnpm
      - uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
        with:
          node-version-file: '.nvmrc'
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - name: Run staging migration
        run: pnpm run migration:deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
