name: CI - DB - Staging

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflows }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: "Deploy Staging DB"
    environment: AWS Staging DB
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - run: corepack enable pnpm
      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version-file: ".nvmrc"
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - name: Run staging migration
        run: pnpm run migration:deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
