name: Release Apps

on:
  release:
    types: [published]
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths-ignore:
      - "apps/web/**"
      - "packages/**"

permissions:
  id-token: write
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

env:
  APPS: "bridge-api"

jobs:
  aws_ecr:
    name: Publish AWS ECR
    environment: AWS ECR
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [bridge-api]
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838 # v1.7.0
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::738942439028:role/GITHUB_OIDC_WAVESHQ_BRIDGE_ECR
          role-duration-seconds: 900

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@2f9f10ea3fa2eed41ac443fee8bfbd059af2d0a4 # v1.6.0
        with:
          registry-type: public

      - name: Resolve ECR Tags
        uses: actions/github-script@d556feaca394842dc55e4734bf3bb9f685482fa0 # v6.3.3
        id: ecr-tags
        with:
          script: return require('./.github/scripts/release-ecr-tags.js')({ context })
          result-encoding: string

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: public.ecr.aws/w1x3w8l6
          IMAGE_TAG: bridge-api:${{ steps.ecr-tags.outputs.result }}
        run: |
          docker build --file apps/server/Dockerfile -t $ECR_REGISTRY/$IMAGE_TAG .
          docker push $ECR_REGISTRY/$IMAGE_TAG

# TODO Check why failing permissions
#  report:
#    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]'
#    name: Report
#    runs-on: ubuntu-latest
#    needs: [ghcr, aws_ecr]
#    steps:
#      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
#
#      - name: Create Report
#        uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975 # v6.4.0
#        id: report_message
#        with:
#          script: return require('./.github/scripts/release-report.js')({ context })
#          result-encoding: string
#
#      - name: Post Report
#        uses: marocchino/sticky-pull-request-comment@3d60a5b2dae89d44e0c6ddc69dd7536aec2071cd # v2.5.0
#        with:
#          header: release
#          message: ${{ steps.report_message.outputs.result }}
